### ISSUE TITLE
Can't access from Wallet

### ISSUE THREAD

**Issue by BigBruiser34** [vexchange/info#10]
Good morning. I put 100,000 VeChain from my Crypto.com wallet to vexchange.io about 3 weeks ago. My son mistakenly cleared the history on my phone and now I can not access the wallet. I never backed the wallet up with the extended password and every time I try to access the wallet it makes me start a new one. Any idea how I can get my original wallet open? Thanks so much for your help.

**Comment by KennethAshley** [comment]
@BigBruiser34 mind joining our Discord? We can chat about possible solutions better over there.

**Comment by BigBruiser34** [comment]
I am sorry how would I join the discord

**Comment by BigBruiser34** [comment]
I found the discord but I can not access it from work.  I will get on tonight from my house. Thanks for your help.

**Comment by KennethAshley** [comment]
@BigBruiser34 try this https://discord.gg/krPDhtcumr

**Comment by OliverNChalk** [comment]
Issue is not related to `info`, if discord doesn't work feel free to reply here but I will mark the issue closed from a dev perspective
